### ISSUE TITLE
Is it possible to run without a router as an access point?

### ISSUE THREAD

**Issue by Meins321** [JohnHalfords/Timer-Clock-program-for-the-ESP8266#1]
I would like to run it without an router on batterys stand alone.

Is it possible to run in access point mode and redirect anything to the Website of the timer?

So a Smartphone or Tablett can be used to login and control/setup?

**Comment by Meins321** [comment]
I have looked at the "info" page and in the user declaration files too.

Is it possible to set the time by values manually or add an rtc to keep time if power goes out?

I am asking because the website the project itself serves looks very baseline and clean and I like it I have to say!!

**Comment by JohnHalfords** [comment]
Hello Moritz,

Thanks for your interesting question.
The answer is Yes, but not without changes to the code.

The code assumes you get an ip-adress from a dhcp server which is in most home situations a router AND the code 'talks' to a time server, which is on the internet.
So, you have to dive into the code to create a possibility to enter the time (would be nice to be able to do that though the web interface) and not get it from the net AND you have to delete the DHCP part and enter the ip-address manually.

Note: since this is a question and not an issue i will close this issue after my reply.
You can email me at: halfordsj@gmail.com

With kind regards,
John Halfords, The Netherlands

**Comment by ghost** [comment]
Hallo John,
Is het mogelijk om beide (Zons op en ondergang) te corrigeren met zowel + als -en -   offset. Ik bedoel dus een extra input veld waarin een plus of min wordt ingelezen. Ik heb het geprobeerd, maar mij is het tot op heden niet gelukt. Dat heeft waarschijnlijk te maken dat ik pas op latere leeftijd aan deze materie ben begonnen. (nu 79jr) en 4 jaar geleden pas begonnen. IK begrijp het allemaal wel maar door het  aantal variabelen raak ik de weg kwijt.
Misschien dat jij mij op het juiste spoor kan zetten??? 

Is it possible to correct both (sunrise and sunset) with both + and -and - offset. I mean an extra input field in which a plus or minus is read. I've tried, but so far I haven't succeeded. This probably has to do with the fact that I only started working on this matter at a later age. (now 79yrs) and only started 4 years ago. I understand it all but because of the number of variables I get lost.
Maybe you can put me on the right track???
Bvd,
 Arie Prins  
prins.arie@gmail.com

**Comment by JohnHalfords** [comment]
Hello Arie,

Certainly that is possible, but you have to make it yourself. I thought about it for a long time, but i didn't saw the need for it.

How i would do it:

- Search for the offsets, so the 'MinuteTimerOnOffset[x]' and the 'MinuteTimerOffOffset[x]'
- Repeat these pieces of code by renaming the existing to  'MinuteTimerOnOffsetMin[x]' and 'MinuteTimerOffOffsetPlus[x]' and call the new variables  'MinuteTimerOnOffsetPlus[x]' and the 'MinuteTimerOffOffsetMin[x]'

A lot of work....
What is your need in this? Possibly it can be simpler ...

With kind regards,
John Halfords, The Netherlands

------------------------
Hallo Arie,

Zeker is dat mogelijk, maar dat zul je toch zelf moeten maken. Ik heb er namelijk lang over nagedacht om het in te bouwen, maar zag de noodzaak niet.
Hoe ik te werk zou gaan in dit geval:
- Zoeken op de offsets, dus de 'MinuteTimerOnOffset[x]' en de 'MinuteTimerOffOffset[x]'
- Deze stukjes code dubbel maken door de bestaande te hernoemen naar  'MinuteTimerOnOffsetMin[x]' en 'MinuteTimerOffOffsetPlus[x]' en de nieuwe dus te noemen  'MinuteTimerOnOffsetPlus[x]' en de 'MinuteTimerOffOffsetMin[x]'

Veel werk....
Wat is jouw noodzaak hiervoor? Wellicht kan het eenvoudiger...

With kind regards,
John Halfords, The Netherlands

**Comment by ghost** [comment]
Hallo John,
Bedankt voor je antwoord. Ik had ook al in deze richting gekeken ,vandaar dat ik zei dat ik verdwaalde in het aantal variabelen. 
De reden van veranderen is dat ik jouw software( v.24) al een tijdje tot volle tevredenheid toepas gebruik om mijn rolluiken te bedienen. Helaas verschillen de  daglichttijden in de winter nogal  in vergelijking met de zomer. Dus er moet  worden geswitched tussen plus en min zomer/wintertijd.
Ik zat te denken aan het bijzetten van een LDR, maar ben eerst gaan zoeken naar een software oplossing en denk dat ik toch verder ga hiermee.
Nogmaals bedankt.
Arie Prins
Nb, 
En nu maar hopen dat de zomertijd zal worden afgeschaft. Dan is het probleem ook grotendeels opgelost.!!

Van: John Halfords
Verzonden: maandag 8 november 2021 11:41
Aan: JohnHalfords/Timer-Clock-program-for-the-ESP8266
CC: APteH; Comment
Onderwerp: Re: [JohnHalfords/Timer-Clock-program-for-the-ESP8266] Is it possibleto run without a router as an access point? (#1)

Hallo Arie,
Zeker is dat mogelijk, maar dat zul je toch zelf moeten maken. Ik heb er namelijk lang over nagedacht om het in te bouwen, maar zag de noodzaak niet.
Hoe ik te werk zou gaan in dit geval:
• Zoeken op de offsets, dus de 'MinuteTimerOnOffset[x]' en de 'MinuteTimerOffOffset[x]'
• Deze stukjes code dubbel maken door de bestaande te hernoemen naar 'MinuteTimerOnOffsetMin[x]' en 'MinuteTimerOffOffsetPlus[x]' en de nieuwe dus te noemen 'MinuteTimerOnOffsetPlus[x]' en de 'MinuteTimerOffOffsetMin[x]'
Veel werk....
Wat is jouw noodzaak hiervoor? Wellicht kan het eenvoudiger...
With kind regards,
John Halfords, The Netherlands
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
